name: .NET

on:
  push:
    branches: ["master"]
    paths:
      - api/**
  pull_request:
    branches: ["master"]
    paths:
      - api/**

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      Solution_Name: ./api/WideWorldImporters.sln

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x    
    - name: Restore dependencies
      run: dotnet restore $Solution_Name
    - name: Build
      run: dotnet build $Solution_Name --no-restore
    - name: Test
      run: dotnet test $Solution_Name --no-build --verbosity normal
